services:
  mysql:
    image: 'mysql:8.0.36'
    container_name: 'mysql'
    restart: 'always'
    environment:
      - 'MYSQL_ROOT_PASSWORD=projects'
      - 'MYSQL_USER=projects'
      - 'MYSQL_PASSWORD=projects'
      - 'MYSQL_DATABASE=projects'
    ports:
      - '3306:3306'
    volumes:
      - 'db-data:/var/lib/mysql'

volumes:
  db-data: { }
